### ISSUE TITLE
Teukolsky package does not load properly

### ISSUE THREAD

**Issue by bbonga** [BlackHolePerturbationToolkit/Teukolsky#1]
* note: I also posted this at BlackHolePerturbationToolkit/MathematicaToolkitExamples (not sure which platform would be more appropriate) *

I tried to run the "Teukolsky.nb" example file, but not all the information in the Teukolsky package seems to load properly.
The functions from KerrGeodesics work fine. It loads the information for TeukolskyRadial and TeukolskyRadialFunction defined in the Teukolsky package, however, these functions don't work. The routines MSTRadialUp, MSTRadialIn, SasakiNakamuraRadialUp, etc. are not loaded all together.

Any help appreciated!

(This occurs on my laptop for both Mathematica v11.3 and v12.0)

**Comment by nielsw2** [comment]
The Teukolsky Mathematica package recently went through some major changes following the recent BHPToolkit meeting. This is why the examples and documentation are out of date w.r.t. the code. The new code is looking good so I will merge it with master branch over the weekend and update the documentation/examples.

Thanks for trying out the code. Please do test the new code after the weekend and let us know how it fares.

PS. If you are interested in the Teukolsky package you might also be interested in two other parts of the Toolkit: the [Gremlin package]( https://bhptoolkit.org/GremlinEq/) (Teukolsky solver in C++) and the flux data contained in the [CircularOrbitSelfForceData](https://github.com/BlackHolePerturbationToolkit/CircularOrbitSelfForceData) repository.

**Comment by nielsw2** [comment]
The master branch of the Teukolsky package has been updated to the latest version and the example notebook in the MathematicaExamples repository has also been updated.

The Teukolsky package is still in development but the calculation of the homogeneous radial solutions should work fine (sometimes you may find you need to add extra precision to the inputs).

The calculation of the inhomogeneous solutions and associated fluxes has so far only been implemented for s=-2 and for circular, equatorial orbits.

Let us know if everything now loads correctly.

**Comment by bbonga** [comment]
Thank you. Everything works smoothly now. 

P.S. Also, thanks for pointing out the other parts of the toolkit.
