### ISSUE TITLE
"Amplitudes" not working

### ISSUE THREAD

**Issue by bleather** [BlackHolePerturbationToolkit/Teukolsky#28]
Since the recent changes to add support to s = 2 the amplitudes no longer seem to be working for circular and eccentric orbits with a = 0.  I have attached a screenshot that shows the issue for s = 2.  It seems that the source is mostly convolved but the resulting answer is in terms of a mino time frequency, which seems to be a remnant of the recent additions for more generic sources.
![TeukolskyAmplitudeIssue](https://user-images.githubusercontent.com/29281371/193844302-c5b03ec1-d024-4f0e-8c4c-5a6746d6c338.png)

**Comment by nielsw2** [comment]
Are you using the development branch of KerrGeodesics package? That is needed to access Upsilon_t.
