### ISSUE TITLE
Complex frequencies

### ISSUE THREAD

**Issue by barrywardell** [BlackHolePerturbationToolkit/Teukolsky#29]
The package currently silently produces wrong results when the frequency is not real. This is particularly important as it quite common may want to evaluate the homogeneous solutions at the quasinormal mode frequencies. There are plenty of algorithms that work for quasinormal mode frequencies so we should implement one of them.

**Comment by nielsw2** [comment]
Unless we are sure the result is correct we should change the package to produce no output if omega is complex
