### ISSUE TITLE
Add circular orbit source for s= +/- 1 and s = +2

### ISSUE THREAD

**Issue by nielsw2** [BlackHolePerturbationToolkit/Teukolsky#3]
Currently the source for circular orbits is missing for s = {-1,+1,+2}. These should be added.

**Comment by barrywardell** [comment]
The s=-1 case is implemented in pull request #9.

**Comment by barrywardell** [comment]
The s=+1 case is also now implemented.

**Comment by znasipak** [comment]
I may have the s = +2 source, but need to double check

**Comment by barrywardell** [comment]
@znasipak Did you check if you have this? @Kevin-Cunningham was also working on implementing it.

**Comment by znasipak** [comment]
@barrywardell Yes I have some notes with expressions for s = +2 source, but I have not verified them. Has anyone published values to compare to in the literature? If not, it might be worth having @Kevin-Cunningham and I develop separate implementations to make sure we are getting the correct result

**Comment by barrywardell** [comment]
We do have test cases for Schwarzschild circular orbits as we computed both s=+2 and s=-2 in [arXiv:1912.09461](https://arxiv.org/abs/1912.09461). I also have a notebook that checks the Teukolsky-Starobinsky identities are satisfied, so if we have s=+2 and s=-2 then we can check them against each other.

**Comment by barrywardell** [comment]
This has now been implemented as part of pull request #25.
