### ISSUE TITLE
TeukolskyPointParticleMode[s,l,m,n,k,orbit]["Radial"] not working

### ISSUE THREAD

**Issue by LeanneDurkan** [BlackHolePerturbationToolkit/Teukolsky#33]
When TeukolskyPointParticleMode[s,l,m,n,k,orbit]["Radial"] is called, specifying the orbit using KerrGeoOrbit, nothing is returned. The fluxes and other quantities however are still working, for exampl TeukolskyPointParticleMode[s,l,m,n,k,orbit]["Fluxes"] returns a value.

**Comment by Kevin-Cunningham** [comment]
"RadialFunctions" should work. Also worth noting that in the most up-to-date version implements the Keys function, so you can see what's available and how to call it.

**Comment by nielsw2** [comment]
I'm going to re-open this issue as a reminder that we need to update the documentation.

**Comment by LeanneDurkan** [comment]
Are we sure that TeukolskyPointParticleMode are inhomogeneous solutions? I think they give the same answer as the TeukolskyRadial function, which are the homogeneous solutions.

**Comment by LeanneDurkan** [comment]
Thanks Kevin. The documentation seems to suggest that it gives the inhomogeneous solution, especially as you need to specify an orbit. Might also be worth updating this.

**Comment by barrywardell** [comment]
There have been several improvements in this area in the master branch, which we are aiming to turn into a new release soon. See #18 for example. Hopefully with that release it will be quite explicitly clear when you are getting homogeneous or inhomogeneous solutions.

Where in the documentation does it suggest you are getting the inhomogeneous solution? We should certainly fix that.

**Comment by LeanneDurkan** [comment]
Thanks Barry, looking forward to the new release!

In the tutorial Teukolsky.nb it gives the inhomogeneous equation, and also has a section about inhomogeneous solutions.

**Comment by barrywardell** [comment]
The tutorial has been updated.
