### ISSUE TITLE
Package fails to load on M1 Macs for Mathematica 13.1

### ISSUE THREAD

**Issue by bleather** [BlackHolePerturbationToolkit/Teukolsky#34]
The package fails to load on my ARM M1 Mac for Mathematica 13.1.  It seems linked to a previous issue I raised with `h5mma`.

When trying to load the latest version of the package, you get the following error:
`h5mma has been installed, but the MathLink executable cannot be loaded. Please check the README for instructions for filing a bug report.` before the kernel aborts loading the Teukolsky package.

I know `h5mma` has issues with M1 Macs due to the architecture change, but I'm unsure how to find a workaround to make the package work.  I don't know if anyone else has experienced similar issues.

**Comment by znasipak** [comment]
Do you know what part of the package relies on `h5mma`?

**Comment by nielsw2** [comment]
The code will fall back to Mathematica's (slower) HDF5 reader if the `h5mma` package is not found. If you uninstall the h5mma package this should resolve the issue.

**Comment by barrywardell** [comment]
We could consider removing h5mma, at least until we decide to include the series expansions.

**Comment by barrywardell** [comment]
This has been fixed in aadb792f2d3b8fdde84b6dc331d12e508de53d8f. The fix was to remove the dependence on h5mma.
