### ISSUE TITLE
Using TeukolskyPointParticleMode with ParallelTable

### ISSUE THREAD

**Issue by bleather** [BlackHolePerturbationToolkit/Teukolsky#35]
I asked Niels last week about a problem I have been having with the new Teukolsky package.  If, for instance, you wanted to compute a large number of point particle modes and wanted to parallelise this with ParallelTable, I assumed you would have to pass ParallelNeeds[“Teukolsky`”] for this to distribute the definitions to all of the Kernels.  

This doesn’t seem to work for me for the latest version of the Teukolsky package on GitHub.  I attempted to PacletInstall the new package on each Kernel, but this gives error messages that I cannot access the TeukolskyRadial or ConvolveSource definitions, e.g.
`Set::shape :  Lists {Teukolsky`ConvolveSource`Private`\[CapitalDelta]tr$2566,Teukolsky`ConvolveSource`Private`\[CapitalDelta]\[Phi]r$2566} and {\[CapitalDelta]tr,\[CapitalDelta]\[Phi]r}/. Missing[KeyAbsent,TrajectoryDeltas] are not the same shape. `

Is there currently a workaround for this or have I missed something?

**Comment by barrywardell** [comment]
The [example notebook from the Einstein Toolkit tutorial](https://einsteintoolkit.github.io/et2021uiuc/lectures/22-BarryWardell/index.html) uses parallel evaluation with the Teukolsky package. Have you tried that to see if it works?

**Comment by barrywardell** [comment]
There's also another example from the [Scattering and Absorption](https://icerm.brown.edu/programs/sp-f20/w1/ScatteringAndAbsorbtion-Solution.nb) tutorial at ICERM.

**Comment by barrywardell** [comment]
Closing this, since the example notebook seems to work.
