### ISSUE TITLE
Failed to compute Wronskian directly from homogeneous solutions

### ISSUE THREAD

**Issue by ricokaloklo** [BlackHolePerturbationToolkit/Teukolsky#36]
Hi,

While I know that you can compute what the (scaled) Wronskian should be from the asymptotic amplitudes that the MST method is very good at calculating (both in terms of speed and accuracy), I want to take the "naive" approach and calculate it directly from the homogeneous solutions at a few different locations/radii.

More explicitly, I am using the following lines of code:

```Mathematica
<< Teukolsky`

s = -2; l = 2; m = 2; a = 0.7`64; \[Omega] = 1.0`64;
RinRup = TeukolskyRadial[s, l, m, a, \[Omega]]; Rin = 
 RinRup[["In"]]; Rup = RinRup[["Up"]];
\[ScriptCapitalW]R = (r^2 - 2 r + a^2)^(
   s + 1)*(Rin[r]*D[Rup[r], r] - Rup[r]*D[Rin[r], r]);
```

Calculating the Wronskian with this at rstar/M = 0 works fine:
![image](https://github.com/BlackHolePerturbationToolkit/Teukolsky/assets/55488840/ca786757-1002-472c-9ac5-05f88c5461f5)

Not so much at rstar/M = 50 (and beyond):
![image](https://github.com/BlackHolePerturbationToolkit/Teukolsky/assets/55488840/0bc43d58-faa5-4716-954f-368368d36b16)
and going to the other direction at rstar/M = -50, while Mathematica did not out right give me an error like the above, it is taking at least an hour to compute (I aborted the computation after an hour).

Have I done something stupid here? Or is it fair to say that this is a limitation of the MST method being used here?

Thank you so much in advance!

**Comment by nielsw2** [comment]
I think, as you guessed, the MST method does not work well in this domain. Omega = 1 is quite a large frequency and certainly for rstar/M = -50 the Up the convergence of the Up solution will be extremely poor.

You can also use the option Method -> "Numericallntegration" for an alternative approach. This can be very slow for high precision input but is faster for machine precision input.

**Comment by barrywardell** [comment]
Another brute force option is to work at higher precision. I've checked that for your test case 128 digit precision is sufficient to accurately compute the Wronskian.
