### ISSUE TITLE
Add the static modes

### ISSUE THREAD

**Issue by nielsw2** [BlackHolePerturbationToolkit/Teukolsky#4]
The static modes are missing from the package (needed for, e.g., self-force calculations). 

Worth noting there are two classes. Both have omega = 0, but may or may not have m = 0. See Secs. III.B.2 and 3 of https://arxiv.org/pdf/1506.04755.pdf.

**Comment by barrywardell** [comment]
These were added in commits 60ba66d and 85d7542.
