### ISSUE TITLE
HeunC method cannot produce derivatives of Up solutions

### ISSUE THREAD

**Issue by znasipak** [BlackHolePerturbationToolkit/Teukolsky#44]
Because the Up solutions are defined in terms of a complex conjugate operation, taking derivatives of the solution does not give a meaningful result since complex conjugation is not analytic. We will need to derive an independent expression for the derivative of the Up solution with respect to the HeunC solutions.

**Comment by barrywardell** [comment]
I don't think we need to derive separate expressions for the derivative. In this case it's safe to commute the complex conjugation with the derivative. The only tricky bit is coaxing Mathematica to be less careful with Conjugate. One possibility is using something like the following:
```Mathematica
excluded = "ExcludedFunctions" /. ("DifferentiationOptions" /. SystemOptions["DifferentiationOptions"]);
SetSystemOptions[
  "DifferentiationOptions" -> 
   "ExcludedFunctions" -> Union[excluded, {conj}]];
conj /: D[conj[f_], x__] := conj[D[f, x]];
conj[x_?NumericQ] := Conjugate[x];
```
