### ISSUE TITLE
Numerical integration unreliable for low values of r

### ISSUE THREAD

**Issue by znasipak** [BlackHolePerturbationToolkit/Teukolsky#45]
The `NumericalIntegration` method does not always produce accurate solutions, particularly for small values of `r`. This leads to the `TeukolskyPointParticleMode` returning inaccurate results for closely bound, eccentric orbits. For example, consider an orbit evaluated at two levels of precision
```
geo = KerrGeoOrbit[0.9`60, 2.8442394157750286`60, 0.49759236333609846`60, 1];
geo2 = KerrGeoOrbit[0.9`80, 2.8442394157750286`80, 0.49759236333609846`80, 1];
```
We then construct Teukolsky solutions via numerical integration
```
l = 6;
m = 6;
n = 6;
rmin = geo["p"]/(1 + geo["e"]);
rmax = geo["p"]/(1 - geo["e"]);
rmin2 = geo2["p"]/(1 + geo2["e"]);
rmax2 = geo2["p"]/(1 - geo2["e"]);
omega = Dot[Values[geo["Frequencies"]][[;; 3]]/Values[geo["Frequencies"]][[4]], {n, 0, m}];
omega2 = Dot[Values[geo2["Frequencies"]][[;; 3]]/Values[geo2["Frequencies"]][[4]], {n, 0, m}];
Rt = TeukolskyRadial[-2, l, m, geo["a"], omega, Method -> {"NumericalIntegration", "Domain"->{"In"->{rmin, rmax}, "Up"->{rmin, rmax}}}];
Rt2 = TeukolskyRadial[-2, l, m, geo2["a"], omega2, Method -> {"NumericalIntegration", "Domain"->{"In"->{rmin2, rmax2}, "Up"->{rmin2, rmax2}}}];
```
Then evaluating 
```
Abs[1 - Rt["Up"][Array[# &, 11, {rmin, rmax}]]/Rt2["Up"][Array[# &, 11, {rmin2, rmax2}]]] // N
Abs[1 - Rt["In"][Array[# &, 11, {rmin, rmax}]]/Rt2["In"][Array[# &, 11, {rmin2, rmax2}]]] // N
```
returns the results
```
{1.96943*10^-14, 0.276401, 0.231586, 0.137476, 0.0902694, 0.302733, \
0.0588866, 0.0703872, 0.0167911, 0.0310057, 0.00332751, 0.00962631, \
0.00535341, 0.00113264, 0.000922653, 0.00031338, 0.000394272, \
0.0000134206, 0.000017826, 2.71715*10^-16}
{5.64993*10^-21, 0.0000131911, 0.000130221, 0.0000843978, \
0.000489572, 0.000111358, 0.000440316, 0.00201323, 0.00256155, \
0.00714126, 0.0067824, 0.0163331, 0.00463274, 0.0144754, 0.0183392, \
0.00789586, 0.00169006, 0.000867674, 0.000200248, 3.10283*10^-21}
```
Increasing the precision does resolve this issue, but this can lead to `TeukolskyPointParticle` returning results that are not as accurate as the user would expect based on the error estimates of `NIntegrate` and the precision of the returned result.

**Comment by barrywardell** [comment]
This seems to be a new issue introduced in version 1.0.1 as a consequence of commit 6b6ae61. Perhaps we should revert that commit and find a different way to avoid the kernel crash that it worked around.

**Comment by znasipak** [comment]
One temporary solution would be wrap the InterpolatingFunction returned by NDSolveValue with another function that we define piecewise to return the interpolated function on the domain and Indeterminate outside of it. For example,
```
sol = NDSolveValue[...];
{xmin, xmax} = sol[[1, 1]];
psi[x_] := Indeterminate;
psi[x_?(xmin <= # <= xmax &)] := sol[x];
```
It's not particularly elegant, but it should work. We could also include an error message when evaluating outside the domain.
