### ISSUE TITLE
TeukolskyPointParticleMode not working for eccentric orbit in static m = n = 0 case 

### ISSUE THREAD

**Issue by srd24** [BlackHolePerturbationToolkit/Teukolsky#47]
Here is a minimal non-working example. I am using Teukolsky-1.0.2. 
```
<< Teukolsky`
orbit = KerrGeoOrbit[0, 10.`30, 0.2`30, 1];
TeukolskyPointParticleMode[0, 2, 0, 0, 0, orbit]
```
The error message begins 
```
TeukolskyRadial::sopt: Option Eigenvalue not supported for static (\[Omega]=0) modes.
```
Is there a workaround?

**Comment by barrywardell** [comment]
This has now been fixed in the newly released version 1.0.3.

**Comment by srd24** [comment]
Thanks Barry!
 I just tried to get version 1.0.3, but it came up with the error message: PacletInstall::dwnld: An error occurred downloading paclet Teukolsky-1.0.3 from site https://pacletserver.bhptoolkit.org: File not found on server..

**Comment by barrywardell** [comment]
Try again now, it should be working this time.

**Comment by srd24** [comment]
Great, it all seems to be working now!
