### ISSUE TITLE
Package fails to load on macOS Catalina Version 10.15.1

### ISSUE THREAD

**Issue by bleather** [BlackHolePerturbationToolkit/Teukolsky#5]
The package fails to load on the newest macOS operating system, Catalina Version 10.15.1.

When trying to load the package the operating system identifies the h5mma HDF5 reader for Mathematica as a potential security issue.

> _“h5mma” cannot be opened because the developer cannot be verified._
> _macOS cannot verify that this app is free from malware._

Mathematica then issues the following warning message before aborting the evaluation:

`h5mma has been installed but the MathLink executable cannot be loaded. Please check the README for instructions for filing a bug report.`

SimulationTools and h5mma are all up to date.

**Comment by barrywardell** [comment]
This is a known issue with h5mma. It only happens if the h5mma package is installed. See https://bitbucket.org/simulationtools/h5mma/issues/11/signing-issues-on-mac-os-1015-catalina for details and workarounds.
