### ISSUE TITLE
Support for complex frequencies

### ISSUE THREAD

**Issue by MvdMeent** [BlackHolePerturbationToolkit/Teukolsky#50]
Is there any hope of getting support for complex frequencies in the Teukolsky package?

**Comment by barrywardell** [comment]
I think it might already work for complex frequencies if you use the HeunC method (you might need to disable the check that makes the functions only evaluate for real frequency). It should also be possible to get the MST method working for complex frequencies. I think most things go through unchanged but right now it fails so there will need to be at least some changes.

**Comment by barrywardell** [comment]
There is at least one place where there is a problem. As found by @bleather:

> On [line 126-128 of `RenormalisedAngularMomentum.m`](https://github.com/BlackHolePerturbationToolkit/Teukolsky/blob/master/Kernel/MST/RenormalizedAngularMomentum.m#L126) there is the following function:
> ```Mathematica
> If[Precision[Cos2\[Pi]\[Nu][nmax]]=!=MachinePrecision,
>     Cos2\[Pi]\[Nu][nmax] = N[Cos2\[Pi]\[Nu][nmax], Max[-RealExponent[Im[Cos2\[Pi]\[Nu][nmax]]/Re[Cos2\[Pi]\[Nu][nmax]]],0]];
>   ];
> ```
> When you have an imaginary component to the frequency, this If statement will truncate the precision to 0, which breaks the continued fraction within the MST method.  We suggest changing the function within to taking the minimum of the precision between the real and imaginary parts, rather than the ratio.  This way, the real and imaginary components will have the same precision.  We have performed limited tests and removing this If statement as a first pass seems to work, as we can now evaluate the Teukolsky functions for complex frequencies.

**Comment by barrywardell** [comment]
Looking at this further, there are a couple of other places where it is assumed that $\cos(2\pi \nu)$ is real in order to estimate the precision of the result. To fix this fully, we would need to find another way to gauge the precision of the calculation of $\nu$.

**Comment by MvdMeent** [comment]
One (relatively expensive) way would be to test how well nu solves the continued fraction equation.

**Comment by barrywardell** [comment]
This is now implemented in pull request #54. Basic testing suggests everything works fine.

**Comment by barrywardell** [comment]
I have verified that the solutions produced for QNM frequencies is correct by comparing it against the [QNM](https://github.com/BlackHolePerturbationToolkit/QNM-Mathematica) Mathematica code.
