### ISSUE TITLE
Checks for MST package

### ISSUE THREAD

**Issue by LeanneDurkan** [BlackHolePerturbationToolkit/Teukolsky#7]
Need to check MSTRadialIn and MSTRadialUp and their derivatives evaluate correctly for the ReggeWheeler option.

The accuracy of derivatives of MSTRadialUp for Teukolsky may want to be improved.

Amplitudes may also need updating.

**Comment by LeanneDurkan** [comment]
The accuracy of the derivatives of MSTRadialUp for Teukolsky has been resolved

**Comment by LeanneDurkan** [comment]
Options do not seem to be working properly. MSTRadial functions produce the same numerical output regardless of choice of MasterFunction

**Comment by LeanneDurkan** [comment]
Internal black parameters have been updated.
RW option needs to be checked.

**Comment by barrywardell** [comment]
I think these issues have all been resolved now that the ReggeWheeler branch has been merged in pull request #6.
